# Site settings
title: inf-2202 fall 2018
# email: firstname.lastname@uit.no
description: > # this means to ignore newlines until "baseurl:"
  Concurrent and data intensive programming. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uit-inf-2202-f18.github.io/" 

# Build settings
markdown: kramdown
